config/routes.rb
Rails.application.routes.draw do
  root 'members#index'
  get '/signup', to: 'members#new'
  resources :members
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :find_member, only: [:show, :edit, :update, :destroy]

  def index
    @members = Member.paginate(page: params[:page])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      flash[:success] = "Member successfully created"
      redirect_to @member
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @member.update(member_params)
      flash[:success] = "Member was successfully updated"
      redirect_to @member
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @member.destroy
      flash[:success] = 'Member was successfully deleted.'
      redirect_to members_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to members_url
    end
  end

  private

  def find_member
    @member = Member.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<ul>
  <% @member.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= form_with(model: @member, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit yield(:button_text) %>
<% end %>

app/views/members/edit.html.erb
<% provide(:title, 'Edit account') %>
<% provide(:button_text, 'Update Profile') %>

<h1>Edit account</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<% provide(:title, 'All Members') %>

<h1>Members List:</h1>

<%= will_paginate %>

<% @members.each do |member| %>
  <p><%= member.name %></p>
  <p><%= member.email %></p>
  <p>
    <%= link_to "Show", member %> | 
    <%= link_to "Edit", edit_member_path(member) %> | 
    <%= link_to "Delete", member, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
  <br>
<% end %>

<%= will_paginate %>

<%= link_to 'Signup', signup_path %>
<%# <%= link_to 'Login', login_path %> %>

app/views/members/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:button_text, 'Create my account') %>

<h1>Signup</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p><%= @member.name %></p>
<p><%= @member.email %></p>
<p>
  <%= link_to "Show", @member %> | 
  <%= link_to "Edit", edit_member_path(@member) %> | 
  <%= link_to "Delete", @member, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<%= link_to 'Back', members_path %>